name: Run Discord Bot

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up the token from GitHub Secrets
        run: |
          echo "TOKEN_BOT_DISCORD=${{ secrets.TOKEN_BOT_DISCORD }}" >> .env

      - name: Run the bot
        run: |
          python main.py
